<?php 
require('css.php');
require('header.php');
require('aside.php');
require('header_section.php');
require('konten.php');
require('footer.php');
//require('control_sidebar.php');
require('js.php');
